Performance Improvement - Perform test filtering earlier in process
machine/machine.specifications pull request #433
Opened 2021-04-16 13:29 UTC by neilrees

Move the filtering to `AssemblyExplorer` where filtering can be carried out before the `Context` is created which involves creating an instance of the test class.  Filtering can be done just by using the `Type` and is much faster then there are a large number specifications in the test assembly, as it saves instantiating a context for each specification.  Sorting by namespace is now carried out after the filter to reduce the size of the sort required.

There is a slight change in behaviour, if an illegal test (e.g. test with two establishes) is excluded from the run, it no longer is called out as an error whereas it did previously.   Previously the `ContextFactory` would have failed to create a context for the illegal test, but now the test is excluded (by tags or class name) before the context is created so the error is not reported.  The error is still reported when the bad test is included in the test run.

2021-04-18 11:02 UTC, robertcoltheart commented
Thanks for this, I'll look at it in more detail. I think the change in behavior is not significant, and probably makes more sense given the filtering mechanism anyway.

2021-04-24 11:19 UTC, robertcoltheart requested changes
Couple of nits, thanks

2021-04-24 11:19 UTC, robertcoltheart commented on src/Machine.Specifications/Utility/KeyValuePairExtensions.cs
> +    static class KeyValuePairExtensions
```suggestion
    internal static class KeyValuePairExtensions
```

2021-04-24 11:19 UTC, robertcoltheart commented on src/Machine.Specifications/Explorers/AssemblyExplorer.cs
> +                if (includeTags.Any() )
```suggestion
                if (includeTags.Any())
```

2021-04-24 11:19 UTC, robertcoltheart commented on src/Machine.Specifications/Explorers/AssemblyExplorer.cs
> +                if (excludeTags.Any() )
```suggestion
                if (excludeTags.Any())
```

2021-04-24 11:46 UTC, neilrees commented
Thanks for the review, feedback applied

2021-04-24 12:10 UTC, merged